<a href="https://colab.research.google.com/github/aniruddhabhagwatkar/Data_Science_Lab_SE_04/blob/main/Ex_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Create a 3x3 square matrix
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 Matrix A:")
print(matrix_a)

# Compute its determinant
det_a = np.linalg.det(matrix_a)

print("\nDeterminant of Matrix A:")
print(det_a)

Original 3x3 Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix A:
0.0


In [5]:
import numpy as np

# Create an invertible 3x3 matrix
matrix_b = np.array([
    [4, 2, 1],
    [3, 5, 2],
    [1, 1, 6]
])

print("Original 3x3 Matrix B:")
print(matrix_b)

# Compute its determinant
det_b = np.linalg.det(matrix_b)

print("\nDeterminant of Matrix B:")
print(det_b)

# Compute the inverse of Matrix B
inverse_matrix_b = np.linalg.inv(matrix_b)

print("\nInverse of Matrix B:")
print(inverse_matrix_b)

Original 3x3 Matrix B:
[[4 2 1]
 [3 5 2]
 [1 1 6]]

Determinant of Matrix B:
78.0

Inverse of Matrix B:
[[ 0.35897436 -0.14102564 -0.01282051]
 [-0.20512821  0.29487179 -0.06410256]
 [-0.02564103 -0.02564103  0.17948718]]


In [6]:
import numpy as np

# Define the coefficients matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constants vector B
B = np.array([
    10,
    20
])

# Solve the system of linear equations
solution = np.linalg.solve(A, B)

x = solution[0]
y = solution[1]

print(f"Solution for x: {x}")
print(f"Solution for y: {y}")

Solution for x: 5.0
Solution for y: 0.0
